/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ClientPlaces.h"

bool_t
xdr_places (XDR *xdrs, places *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->code, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->state, 3,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dist))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (places), (xdrproc_t) xdr_places))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_city (XDR *xdrs, city *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->state, 3,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->city, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnTypeC (XDR *xdrs, returnTypeC *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->returnTypeC_u.resultC, sizeof (places), (xdrproc_t) xdr_places))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
