/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ClientPlaces.h"

returnTypeC *
ctop_1_svc(city *argp, struct svc_req *rqstp)
{
	static returnTypeC  result;

	/*
	 * insert server code here
	 */

	return &result;
}
