/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PlacesAirport.h"


void
places_airport_1(char *host)
{
	CLIENT *clnt;
	returnTypeA  *result_1;
	LatLon  ptoa_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PLACES_AIRPORT, PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ptoa_1(&ptoa_1_arg, clnt);
	if (result_1 == (returnTypeA *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	places_airport_1 (host);
exit (0);
}
