/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PlacesAirport.h"

returnTypeA *
ptoa_1_svc(LatLon *argp, struct svc_req *rqstp)
{
	static returnTypeA  result;

	/*
	 * insert server code here
	 */

	return &result;
}
